### ISSUE TITLE
Error , can't add it to the pubspec.yaml

### ISSUE THREAD

**Issue by romangazi121** [X-SLAYER/device_policy_manager#3]
when i try to add the dependencie at the pubs file i got error . 
![Screenshot 2024-02-15 174158](https://github.com/X-SLAYER/device_policy_manager/assets/149246065/f7a70ff5-a04c-4586-b40a-34b0acfa114a)
![Screenshot 2024-02-16 115421](https://github.com/X-SLAYER/device_policy_manager/assets/149246065/ceef6207-dd98-441e-8179-3988d05278d3)

**Comment by acdwisu** [comment]
change your flutter project name, the name cannot be same as 'device_policy_manager' (this package name)
